Tensors与Numpy中的`ndarrays`类似，但是Tensors可以使用GPU进行计算

In [1]:
from __future__ import print_function
import torch

#### 张量

创建一个矩阵，但未初始化 

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[9.6429e-39, 8.4490e-39, 9.6429e-39],
        [9.2755e-39, 1.0286e-38, 9.0919e-39],
        [8.9082e-39, 9.2755e-39, 8.4490e-39],
        [1.0194e-38, 9.0919e-39, 8.4490e-39],
        [1.0653e-38, 9.9184e-39, 8.4490e-39]])


创建一个随机初始化的矩阵

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0050, 0.9640, 0.6951],
        [0.2694, 0.9330, 0.1498],
        [0.9684, 0.5124, 0.4590],
        [0.7991, 0.2459, 0.9589],
        [0.2554, 0.7225, 0.1297]])


创建一个0填充的矩阵，数据类型为long

In [4]:
x = torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


创建tensor并使用现有数据初始化

In [5]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


根据现有的张量创建张量。 这些方法将重用输入张量的属性，例如， dtype，除非设置新的值进行覆盖

In [6]:
x = x.new_ones(5, 3, dtype = torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
x = torch.randn_like(x, dtype = torch.float)
print(x)

tensor([[-0.2304, -0.0679, -0.3699],
        [ 0.1212,  1.6783, -1.1696],
        [-0.3868, -0.6938,  0.8965],
        [-0.2730, -0.7894,  0.1679],
        [-0.0925,  0.7028, -0.8873]])


获取size

In [8]:
print(x.size())

torch.Size([5, 3])


``torch.Size``返回值类型是tuple类型，所以它支持tuple类型的所有操作

#### 操作

**加法：**

In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.1180,  0.8130, -0.0024],
        [ 0.6888,  2.2415, -0.9589],
        [ 0.1457, -0.4697,  1.1683],
        [ 0.6497, -0.1066,  0.8565],
        [ 0.3935,  1.1625, -0.1332]])


In [10]:
print(torch.add(x, y))

tensor([[ 0.1180,  0.8130, -0.0024],
        [ 0.6888,  2.2415, -0.9589],
        [ 0.1457, -0.4697,  1.1683],
        [ 0.6497, -0.1066,  0.8565],
        [ 0.3935,  1.1625, -0.1332]])


提供输出tensor作为参数：

In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out = result)
print(result)

tensor([[ 0.1180,  0.8130, -0.0024],
        [ 0.6888,  2.2415, -0.9589],
        [ 0.1457, -0.4697,  1.1683],
        [ 0.6497, -0.1066,  0.8565],
        [ 0.3935,  1.1625, -0.1332]])


替换：

In [12]:
y.add_(x)
print(y)

tensor([[ 0.1180,  0.8130, -0.0024],
        [ 0.6888,  2.2415, -0.9589],
        [ 0.1457, -0.4697,  1.1683],
        [ 0.6497, -0.1066,  0.8565],
        [ 0.3935,  1.1625, -0.1332]])


任何以`_`结尾的操作都会用结果替换原变量，例如`x.copy_(y), x.t()`，都会改变x

可以使用与Numpy索引方式相同的操作进行对张量的操作

In [13]:
print(x[:,1])

tensor([-0.0679,  1.6783, -0.6938, -0.7894,  0.7028])


torch.view：可以改变张量的维度和大小
>注：`torch.view与Numpy的shape类似`

In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)   # size -1 从其他维度推断
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


如果你的张量只有一个元素，使用item()来得到Python数据类型的数值

In [24]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.3451])
-0.3451409339904785


> 关于Tensor的更多操作，如转置、切割、数学操作、线性代数、随机数等，详见[here](https://pytorch.org/docs/torch)

#### NumPy转换
Torch Tensor和NumPy数组之间相互转换很容易
共享底层内存地址，修改一个会导致另一个的变化

将一个Torch Tensor转化为NumPy数组

In [16]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [17]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


改变Tensor后，观察numpy数组的值，同时被改变了

In [18]:
a.add(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


NumPy Array 转化为 Torch Tensor（使用`from_numpy`自动转化）

In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out = a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


所有的Tensor类型默认都是基于CPU，==CharTensor==类型不支持到NumPy的转换

#### CUDA张量
使用.to方法可以将Tensor移动到任何设备中

In [20]:
# is_available 函数判断是否有cuda可用
# torch.device 将张量移动到指定设备中
if torch.cuda.is_available():
    device = torch.device("cuda")            # cuda设备对象
    y = torch.ones_like(x, device = device)  # 直接从GPU创建张量
    x = x.to(device)                         # 或者直接用.to("cuda")将张量移动到cuda中
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))         # .to 也会对变量的类型做修改